FROM golang:latest AS builder

WORKDIR /go/src

COPY . .

ENV PATH="/go/bin:${PATH}"

RUN apt-get update

RUN go install

#CMD ["tail", "-f", "/dev/null"]
#CMD ["codeeducation"]

FROM scratch
WORKDIR /go/bin
COPY --from=builder /go/bin/ .
CMD ["/go/bin/codeeducation"]